"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import gc
from dotenv import load_dotenv

# RAM tejash uchun garbage collection optimizatsiyasi
gc.set_threshold(700, 10, 10)  # Tez-tez garbage collection

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env faylini yuklash
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-4qu^cip^$6^ikf-3*e+y47j$0@#mfd%luznci+ey1c2s$pn4-a')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Lokal development uchun yoqilgan

ALLOWED_HOSTS = ['*', '.onrender.com', 'localhost', '127.0.0.1', 'cloudstore.uz', 'www.cloudstore.uz']

# Render.com uchun
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# CSRF sozlamalari (production uchun)
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'https://cloudstore.uz',
    'https://www.cloudstore.uz',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# iOS Safari uchun cookie sozlamalari
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # Lokal uchun False
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Lokal uchun False

# CSRF cookie nomi
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog', 
]

# django_extensions faqat local uchun
try:
    import django_extensions
    INSTALLED_APPS.append('django_extensions')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware
    'blog.middleware.RequestLoggingMiddleware',
    'blog.middleware.OnlineStatusMiddleware',
    'blog.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blog.views_subscription.subscription_context_processor',  # Premium obuna
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

# Production (Render.com) da PostgreSQL, local da SQLite
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'blog', 'static'),
]

# Whitenoise - oddiy storage (hash qo'shmaslik uchun)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Fayllar uchun papkalarni yaratish
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'files'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'images'), exist_ok=True)
os.makedirs(os.path.join(MEDIA_ROOT, 'chat_files'), exist_ok=True)  # Chat fayllari uchun

# Vaqtinchalik fayllar uchun maxsus papka (media/tmp)
import tempfile
TEMP_DIR = os.path.join(MEDIA_ROOT, 'tmp')
os.makedirs(TEMP_DIR, exist_ok=True)

# Django fayl yuklash vaqtinchalik papkasini sozlash
FILE_UPLOAD_TEMP_DIR = TEMP_DIR

# 1MB dan katta fayllar to'g'ridan-to'g'ri diskka yoziladi (RAM tejash uchun)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1048576  # 1MB

# Maksimal upload hajmi (RAM himoyasi)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Session cleanup sozlamalari
SESSION_COOKIE_AGE = 86400  # 1 kun (24 soat)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = False  # Har so'rovda session save qilmaslik

# Shriftlar papkasi
FONTS_ROOT = os.path.join(BASE_DIR, 'fonts')
os.makedirs(FONTS_ROOT, exist_ok=True)

LOGIN_REDIRECT_URL = 'boshlash'
LOGOUT_REDIRECT_URL = 'login'

# Session'larni database'da saqlash (RAM tejash uchun)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# Cache'ni file'ga saqlash (RAM tejash uchun)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache'),
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Maksimal cache entry'lar soni
        }
    }
}

# Cache papkasini yaratish
os.makedirs(os.path.join(BASE_DIR, 'cache'), exist_ok=True)

# Production xavfsizlik sozlamalari
# Render/Cloudflare proksi orqali kelgan so'rovlarni HTTPS deb tushunish uchun
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 yil
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Logging - xatolarni ko'rish uchun
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'blog': {
            'handlers': ['console', 'file'] if not DEBUG else ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Log papkasini yaratish
os.makedirs(os.path.join(BASE_DIR, 'logs'), exist_ok=True)

# ===== EMAIL SOZLAMALARI =====
# Gmail SMTP orqali email yuborish
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'akobirsadiloyev8@gmail.com'
EMAIL_HOST_PASSWORD = 'pssv ntog bvfh kcnb'
DEFAULT_FROM_EMAIL = 'Cloudstore <akobirsadiloyev8@gmail.com>'

# Development uchun console backend (EMAIL_HOST_USER yo'q bo'lsa)
if not EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
