# Generated by Django 6.0.1 on 2026-01-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feedback_user_image_user_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Adib ismi')),
                ('bio', models.TextField(blank=True, verbose_name='Tarjimai hol')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name="Tug'ilgan yili")),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Vafot etgan yili')),
                ('image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Adib',
                'verbose_name_plural': 'Adiblar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Kitob nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('year_written', models.IntegerField(blank=True, null=True, verbose_name='Yozilgan yili')),
                ('file', models.FileField(blank=True, null=True, upload_to='books/', verbose_name='Fayl (PDF/DOCX)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='blog.author', verbose_name='Adib')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['title'],
            },
        ),
    ]
