# Generated by Django 6.0.1 on 2026-01-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, help_text="Fayldan avtomatik o'qilgan to'liq matn", verbose_name='Kitob matni'),
        ),
    ]
