# Generated by Django 6.0.1 on 2026-01-28 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_book_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Sahifa raqami')),
                ('text', models.TextField(verbose_name='Sahifa matni')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.book', verbose_name='Kitob')),
            ],
            options={
                'verbose_name': 'Kitob sahifasi',
                'verbose_name_plural': 'Kitob sahifalari',
                'ordering': ['page_number'],
                'unique_together': {('book', 'page_number')},
            },
        ),
    ]
