# Generated by Django 6.0.1 on 2026-01-28 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_bookpage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='fa-book', max_length=50, verbose_name='Ikonka (FontAwesome)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name="Qidiruv so'zi")),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Qidirilgan soni')),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Qidiruv so'rovi",
                'verbose_name_plural': "Qidiruv so'rovlari",
                'ordering': ['-count'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Muqova rasmi'),
        ),
        migrations.AddField(
            model_name='book',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Baho (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='Sharh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitob bahosi',
                'verbose_name_plural': 'Kitob baholari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_summary', models.TextField(verbose_name='Qisqa xulosa')),
                ('key_points', models.TextField(blank=True, verbose_name='Asosiy fikrlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='blog.book')),
            ],
            options={
                'verbose_name': 'Kitob xulosasi',
                'verbose_name_plural': 'Kitob xulosalari',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='blog.category', verbose_name='Kategoriya'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='blog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sevimli',
                'verbose_name_plural': 'Sevimlilar',
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.PositiveIntegerField(default=1, verbose_name='Hozirgi sahifa')),
                ('total_pages', models.PositiveIntegerField(default=1, verbose_name='Jami sahifalar')),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tugallandi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readers', to='blog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qish progressi",
                'verbose_name_plural': "O'qish progresslari",
                'unique_together': {('user', 'book')},
            },
        ),
    ]
