# Generated by Django 6.0.1 on 2026-01-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_searchquery_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fikr-mulohaza', 'verbose_name_plural': 'Fikr-mulohazalar'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qildi"),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ism'),
        ),
    ]
