# Generated by Django 6.0.1 on 2026-02-01 13:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_book_category_book_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reja nomi')),
                ('plan_type', models.CharField(choices=[('free', 'Bepul'), ('standard', 'Standart'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=20, unique=True)),
                ('duration_type', models.CharField(choices=[('monthly', 'Oylik'), ('quarterly', 'Choraklik (3 oy)'), ('yearly', 'Yillik'), ('lifetime', 'Umrbod')], default='monthly', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Narxi (so'm)")),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asl narxi (chegirma uchun)')),
                ('daily_book_limit', models.PositiveIntegerField(default=3, verbose_name='Kunlik kitob limiti')),
                ('daily_ai_limit', models.PositiveIntegerField(default=5, verbose_name="Kunlik AI so'rov limiti")),
                ('can_download', models.BooleanField(default=False, verbose_name='Yuklab olish')),
                ('can_read_premium', models.BooleanField(default=False, verbose_name="Premium kitoblarni o'qish")),
                ('ads_free', models.BooleanField(default=False, verbose_name='Reklmasiz')),
                ('offline_reading', models.BooleanField(default=False, verbose_name="Offline o'qish")),
                ('referral_bonus', models.PositiveIntegerField(default=0, verbose_name='Referral bonus (kun)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('features', models.JSONField(default=list, verbose_name="Xususiyatlar ro'yxati")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mashhur (badge)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Obuna rejasi',
                'verbose_name_plural': 'Obuna rejalari',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Iqtibos')),
                ('author', models.CharField(max_length=200, verbose_name='Muallif')),
                ('book_title', models.CharField(blank=True, max_length=300, verbose_name='Kitob nomi')),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('show_date', models.DateField(blank=True, null=True, verbose_name="Ko'rsatish sanasi")),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.book')),
            ],
            options={
                'verbose_name': 'Kundalik iqtibos',
                'verbose_name_plural': 'Kundalik iqtiboslar',
                'ordering': ['-show_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('total_invites', models.PositiveIntegerField(default=0, verbose_name='Jami takliflar')),
                ('successful_invites', models.PositiveIntegerField(default=0, verbose_name='Muvaffaqiyatli')),
                ('earned_days', models.PositiveIntegerField(default=0, verbose_name='Yutilgan kunlar')),
                ('earned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral kod',
                'verbose_name_plural': 'Referral kodlar',
            },
        ),
        migrations.CreateModel(
            name='ReferralInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_bonus_given', models.BooleanField(default=False)),
                ('invited_bonus_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invited_by', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.referralcode')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral taklif',
                'verbose_name_plural': 'Referral takliflar',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('code_type', models.CharField(choices=[('percentage', 'Foiz chegirma'), ('fixed', 'Belgilangan summa'), ('days', 'Bonus kunlar'), ('trial', 'Sinov muddati')], default='percentage', max_length=20)),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Qiymat')),
                ('max_uses', models.PositiveIntegerField(default=100, verbose_name='Maksimal foydalanish')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Ishlatilgan')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, to='blog.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Promo kod',
                'verbose_name_plural': 'Promo kodlar',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum', 'Uzum Bank'), ('stripe', 'Stripe'), ('promo', 'Promo kod'), ('referral', 'Referral bonus')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Yakunlangan'), ('failed', 'Muvaffaqiyatsiz'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subscriptionplan')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('read_book', "Kitob o'qish"), ('finish_book', 'Kitob tugatish'), ('rate_book', 'Baho berish'), ('share', 'Ulashish'), ('invite', 'Taklif qilish'), ('login_streak', 'Ketma-ket kirish'), ('first_book', 'Birinchi kitob')], max_length=30)),
                ('points', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faoliyat',
                'verbose_name_plural': 'Faoliyatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_books_read', models.PositiveIntegerField(default=0)),
                ('total_pages_read', models.PositiveIntegerField(default=0)),
                ('total_reading_time', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_active_date', models.DateField(blank=True, null=True)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi statistikasi',
                'verbose_name_plural': 'Foydalanuvchi statistikalari',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('pending', 'Kutilmoqda')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('daily_books_read', models.PositiveIntegerField(default=0)),
                ('daily_ai_requests', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('bonus_days', models.PositiveIntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('reader_1', "Boshlang'ich o'quvchi"), ('reader_10', '10 ta kitob'), ('reader_50', '50 ta kitob'), ('reader_100', 'Kitobxon ustasi'), ('sharer', 'Faol ulashuvchi'), ('reviewer', 'Sharh ustasi'), ('inviter_5', "5 do'st taklifi"), ('inviter_20', 'Influencer'), ('streak_7', 'Haftalik streak'), ('streak_30', 'Oylik streak'), ('first_premium', "Premium a'zo"), ('vip', "VIP a'zo")], max_length=30)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yutuq',
                'verbose_name_plural': 'Yutuqlar',
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
