# Generated by Django 6.0.1 on 2026-02-01 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_bookreview_message_userprofile_follow_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Xabar', 'verbose_name_plural': 'Xabarlar'},
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tahrirlangan'),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Fayl'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Fayl nomi'),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Fayl hajmi (bytes)'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_receiver',
            field=models.BooleanField(default=False, verbose_name="Qabul qiluvchi o'chirgan"),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_by_sender',
            field=models.BooleanField(default=False, verbose_name="Jo'natuvchi o'chirgan"),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_everyone',
            field=models.BooleanField(default=False, verbose_name="Hammadan o'chirilgan"),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('file', 'Fayl'), ('voice', 'Ovozli xabar')], default='text', max_length=10, verbose_name='Xabar turi'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blog.message', verbose_name='Javob'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_typing_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typing_users', to=settings.AUTH_USER_MODEL, verbose_name='Kimga yozmoqda'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_online_status',
            field=models.BooleanField(default=True, verbose_name="Online statusni ko'rsatish"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='typing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Xabar matni'),
        ),
    ]
