# Generated by Django 6.0.1 on 2026-02-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_advanced_chat_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Shtrix kod (Barcode)')),
                ('name', models.CharField(max_length=300, verbose_name='Mahsulot nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Narxi')),
                ('currency', models.CharField(default='UZS', max_length=10, verbose_name='Valyuta')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategoriya')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brend')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Ishlab chiqaruvchi')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Ishlab chiqarilgan mamlakat')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name="Og'irligi")),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('ingredients', models.TextField(blank=True, verbose_name='Tarkibi')),
                ('nutrition_info', models.TextField(blank=True, verbose_name='Ozuqaviy qiymati')),
                ('expiry_info', models.CharField(blank=True, max_length=100, verbose_name='Yaroqlilik muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Skanerlangan soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-scan_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Skanerlangan vaqt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='blog.product', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Skanerlash tarixi',
                'verbose_name_plural': 'Skanerlash tarixi',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
