# Generated by Django 6.0.1 on 2026-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_product_productscanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additives',
            field=models.TextField(blank=True, verbose_name="Qo'shimchalar (E raqamlar)"),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, verbose_name='Allergenlar'),
        ),
        migrations.AddField(
            model_name='product',
            name='calcium',
            field=models.FloatField(blank=True, null=True, verbose_name='Kaltsiy (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='calories',
            field=models.FloatField(blank=True, null=True, verbose_name='Kaloriya (kcal)'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True, verbose_name='Uglevodlar (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='ecoscore_grade',
            field=models.CharField(blank=True, max_length=1, verbose_name='Eco-Score (A-E)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.FloatField(blank=True, null=True, verbose_name="Yog' (g)"),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.FloatField(blank=True, null=True, verbose_name='Kletchatka (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Rasm URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='iron',
            field=models.FloatField(blank=True, null=True, verbose_name='Temir (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='magnesium',
            field=models.FloatField(blank=True, null=True, verbose_name='Magniy (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nova_group',
            field=models.IntegerField(blank=True, null=True, verbose_name='NOVA guruhi (1-4)'),
        ),
        migrations.AddField(
            model_name='product',
            name='nutriscore_grade',
            field=models.CharField(blank=True, max_length=1, verbose_name='Nutri-Score (A-E)'),
        ),
        migrations.AddField(
            model_name='product',
            name='potassium',
            field=models.FloatField(blank=True, null=True, verbose_name='Kaliy (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins',
            field=models.FloatField(blank=True, null=True, verbose_name='Oqsillar (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.FloatField(blank=True, null=True, verbose_name='Tuz (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.FloatField(blank=True, null=True, verbose_name="To'yingan yog' (g)"),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name='Natriy (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars',
            field=models.FloatField(blank=True, null=True, verbose_name='Shakar (g)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_a',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin A (µg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_b1',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin B1 (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_b12',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin B12 (µg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_b2',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin B2 (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_b6',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin B6 (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin C (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_d',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin D (µg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='vitamin_e',
            field=models.FloatField(blank=True, null=True, verbose_name='Vitamin E (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warnings',
            field=models.TextField(blank=True, verbose_name='Ogohlantirishlar'),
        ),
        migrations.AddField(
            model_name='product',
            name='zinc',
            field=models.FloatField(blank=True, null=True, verbose_name='Sink (mg)'),
        ),
    ]
