# Generated by Django 6.0.1 on 2026-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_extended_product_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=6, verbose_name='Tasdiqlash kodi')),
                ('username', models.CharField(max_length=150, verbose_name='Foydalanuvchi nomi')),
                ('password', models.CharField(max_length=255, verbose_name='Parol (hashed)')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlandi')),
                ('attempts', models.IntegerField(default=0, verbose_name='Urinishlar soni')),
            ],
            options={
                'verbose_name': 'Email tasdiqlash',
                'verbose_name_plural': 'Email tasdiqlashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
