# Generated by Django 6.0.1 on 2026-02-04 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_ai_usage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ai_temp/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('expires_at', models.DateTimeField(verbose_name="O'chirilish vaqti")),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='Tahlil natijasi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'AI tahlil rasmi',
                'verbose_name_plural': 'AI tahlil rasmlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
