# Generated by Django 6.0.1 on 2026-02-18 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_ai_analysis_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mahsulot nomi')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Brend')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shtrix kod')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Rasm URL')),
                ('mass', models.FloatField(default=100, verbose_name='Massa (gramm)')),
                ('calories', models.FloatField(default=0, verbose_name='Kaloriya')),
                ('proteins', models.FloatField(default=0, verbose_name='Oqsil (g)')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='Uglevod (g)')),
                ('fat', models.FloatField(default=0, verbose_name="Yog' (g)")),
                ('sugars', models.FloatField(default=0, verbose_name='Shakar (g)')),
                ('salt', models.FloatField(default=0, verbose_name='Tuz (g)')),
                ('fiber', models.FloatField(default=0, verbose_name='Kletchatka (g)')),
                ('calories_per_100g', models.FloatField(default=0, verbose_name='Kaloriya/100g')),
                ('proteins_per_100g', models.FloatField(default=0, verbose_name='Oqsil/100g')),
                ('carbs_per_100g', models.FloatField(default=0, verbose_name='Uglevod/100g')),
                ('fat_per_100g', models.FloatField(default=0, verbose_name="Yog'/100g")),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('snack', 'Gazak')], default='snack', max_length=20, verbose_name='Ovqat turi')),
                ('date', models.DateField(verbose_name='Sana')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('source', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manba')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
            ],
            options={
                'verbose_name': 'Ovqatlanish yozuvi',
                'verbose_name_plural': 'Ovqatlanish yozuvlari',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Adib ismi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=300, verbose_name='Kitob nomi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name'], name='blog_author_name_829872_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='blog_book_title_41da13_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', '-created_at'], name='blog_book_author__180386_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-views_count'], name='blog_book_views_c_8d0675_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='blog_book_created_1ddff4_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', '-views_count'], name='blog_book_author__5c9a68_idx'),
        ),
        migrations.AddField(
            model_name='foodintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_intakes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddIndex(
            model_name='foodintake',
            index=models.Index(fields=['user', 'date'], name='blog_foodin_user_id_8bcba9_idx'),
        ),
        migrations.AddIndex(
            model_name='foodintake',
            index=models.Index(fields=['date'], name='blog_foodin_date_f9f117_idx'),
        ),
    ]
