# Taomlar, salatlar va desertlar uchun ozuqaviy ma'lumotlar bazasi
# 100 gramm uchun hisoblangan

FOOD_DATA = {
    # ============ SALATLAR ============
    "achchiq-chuchuk": {
        "name": "Achchiq-chuchuk",
        "category": "salat",
        "image": "assets/img/salatlar/acchiq_chuchuk.jpg",
        "calories": 50,
        "protein": 1.5,
        "fat": 3,
        "carbs": 5,
        "fiber": 1.5,
        "sugar": 3,
        "saturated_fat": 0.3,
        "unsaturated_fat": 2.5,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 25, "C": 35, "D": 0, "E": 8, "K": 15, "B6": 10},
        "minerals": {"sodium": 380, "potassium": 220, "calcium": 20, "iron": 5},
        "gi_index": 15,
        "positive_percent": 80,
        "negative_percent": 20,
    },
    "olivye": {
        "name": "Olivye",
        "category": "salat",
        "image": "assets/img/salatlar/olivier_salad.jpg",
        "calories": 190,
        "protein": 5,
        "fat": 14,
        "carbs": 12,
        "fiber": 2,
        "sugar": 2,
        "saturated_fat": 2.5,
        "unsaturated_fat": 10,
        "trans_fat": 0.2,
        "cholesterol": 45,
        "vitamins": {"A": 15, "C": 15, "D": 2, "E": 5, "K": 10, "B6": 12},
        "minerals": {"sodium": 520, "potassium": 350, "calcium": 40, "iron": 8},
        "gi_index": 45,
        "positive_percent": 50,
        "negative_percent": 50,
    },
    "sezar": {
        "name": "Sezar",
        "category": "salat",
        "image": "assets/img/salatlar/sezar.jpg",
        "calories": 180,
        "protein": 8,
        "fat": 12,
        "carbs": 10,
        "fiber": 2,
        "sugar": 2,
        "saturated_fat": 3,
        "unsaturated_fat": 8,
        "trans_fat": 0.1,
        "cholesterol": 35,
        "vitamins": {"A": 30, "C": 20, "D": 1, "E": 6, "K": 45, "B6": 8},
        "minerals": {"sodium": 480, "potassium": 280, "calcium": 120, "iron": 10},
        "gi_index": 35,
        "positive_percent": 60,
        "negative_percent": 40,
    },
    "yunoncha-salat": {
        "name": "Yunoncha salat",
        "category": "salat",
        "image": "assets/img/salatlar/yunoncha salat.jpg",
        "calories": 120,
        "protein": 4,
        "fat": 9,
        "carbs": 6,
        "fiber": 2,
        "sugar": 4,
        "saturated_fat": 4,
        "unsaturated_fat": 5,
        "trans_fat": 0,
        "cholesterol": 20,
        "vitamins": {"A": 25, "C": 30, "D": 0, "E": 10, "K": 30, "B6": 6},
        "minerals": {"sodium": 600, "potassium": 250, "calcium": 100, "iron": 8},
        "gi_index": 20,
        "positive_percent": 75,
        "negative_percent": 25,
    },
    "mimoza": {
        "name": "Mimoza",
        "category": "salat",
        "image": "assets/img/salatlar/mimoza.jpg",
        "calories": 200,
        "protein": 10,
        "fat": 15,
        "carbs": 8,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 3,
        "unsaturated_fat": 10,
        "trans_fat": 0.2,
        "cholesterol": 120,
        "vitamins": {"A": 20, "C": 10, "D": 8, "E": 5, "K": 8, "B6": 15},
        "minerals": {"sodium": 450, "potassium": 300, "calcium": 50, "iron": 12},
        "gi_index": 40,
        "positive_percent": 55,
        "negative_percent": 45,
    },
    "sabzavotli-salat": {
        "name": "Sabzavotli salat",
        "category": "salat",
        "image": "assets/img/salatlar/sabzavotli salat.jpg",
        "calories": 70,
        "protein": 2,
        "fat": 4,
        "carbs": 7,
        "fiber": 3,
        "sugar": 4,
        "saturated_fat": 0.5,
        "unsaturated_fat": 3,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 40, "C": 45, "D": 0, "E": 10, "K": 50, "B6": 12},
        "minerals": {"sodium": 120, "potassium": 350, "calcium": 35, "iron": 6},
        "gi_index": 15,
        "positive_percent": 85,
        "negative_percent": 15,
    },
    "bodring-pomidor": {
        "name": "Bodring-pomidor",
        "category": "salat",
        "image": "assets/img/salatlar/bodring-pomidor.jpg",
        "calories": 60,
        "protein": 1.5,
        "fat": 4,
        "carbs": 5,
        "fiber": 1.5,
        "sugar": 3,
        "saturated_fat": 0.5,
        "unsaturated_fat": 3,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 20, "C": 25, "D": 0, "E": 8, "K": 20, "B6": 8},
        "minerals": {"sodium": 150, "potassium": 280, "calcium": 20, "iron": 5},
        "gi_index": 15,
        "positive_percent": 85,
        "negative_percent": 15,
    },
    "kartoshka-salati": {
        "name": "Kartoshka salati",
        "category": "salat",
        "image": "assets/img/salatlar/kartoshkali.jpg",
        "calories": 150,
        "protein": 3,
        "fat": 10,
        "carbs": 14,
        "fiber": 2,
        "sugar": 2,
        "saturated_fat": 1.5,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 15,
        "vitamins": {"A": 5, "C": 15, "D": 0, "E": 5, "K": 8, "B6": 15},
        "minerals": {"sodium": 400, "potassium": 450, "calcium": 25, "iron": 8},
        "gi_index": 55,
        "positive_percent": 55,
        "negative_percent": 45,
    },
    "tovuq-salati": {
        "name": "Tovuq salati",
        "category": "salat",
        "image": "assets/img/salatlar/tovuq salat.jpg",
        "calories": 160,
        "protein": 14,
        "fat": 10,
        "carbs": 4,
        "fiber": 1,
        "sugar": 2,
        "saturated_fat": 2,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 50,
        "vitamins": {"A": 15, "C": 10, "D": 1, "E": 5, "K": 15, "B6": 25},
        "minerals": {"sodium": 380, "potassium": 300, "calcium": 30, "iron": 10},
        "gi_index": 25,
        "positive_percent": 65,
        "negative_percent": 35,
    },
    "baliqli-salat": {
        "name": "Baliqli salat",
        "category": "salat",
        "image": "assets/img/salatlar/baliqli salat.jpg",
        "calories": 170,
        "protein": 15,
        "fat": 11,
        "carbs": 3,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 2,
        "unsaturated_fat": 8,
        "trans_fat": 0,
        "cholesterol": 45,
        "vitamins": {"A": 10, "C": 8, "D": 15, "E": 8, "K": 10, "B6": 20},
        "minerals": {"sodium": 450, "potassium": 350, "calcium": 40, "iron": 8},
        "gi_index": 20,
        "positive_percent": 65,
        "negative_percent": 35,
    },
    "qovoq-salati": {
        "name": "Qovoq salati",
        "category": "salat",
        "image": "assets/img/salatlar/qovoq.jpg",
        "calories": 80,
        "protein": 2,
        "fat": 5,
        "carbs": 8,
        "fiber": 2,
        "sugar": 4,
        "saturated_fat": 0.5,
        "unsaturated_fat": 4,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 80, "C": 15, "D": 0, "E": 8, "K": 10, "B6": 10},
        "minerals": {"sodium": 100, "potassium": 400, "calcium": 25, "iron": 6},
        "gi_index": 35,
        "positive_percent": 75,
        "negative_percent": 25,
    },
    "lavlagi-salati": {
        "name": "Lavlagi salati",
        "category": "salat",
        "image": "assets/img/salatlar/lavlagi.jpg",
        "calories": 90,
        "protein": 2,
        "fat": 5,
        "carbs": 10,
        "fiber": 2.5,
        "sugar": 7,
        "saturated_fat": 0.5,
        "unsaturated_fat": 4,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 5, "C": 10, "D": 0, "E": 5, "K": 15, "B6": 8},
        "minerals": {"sodium": 250, "potassium": 380, "calcium": 20, "iron": 15},
        "gi_index": 45,
        "positive_percent": 80,
        "negative_percent": 20,
    },
    "kokatli-salat": {
        "name": "Ko'katli salat",
        "category": "salat",
        "image": "assets/img/salatlar/kokatli salat.jpg",
        "calories": 40,
        "protein": 2,
        "fat": 2,
        "carbs": 4,
        "fiber": 2,
        "sugar": 2,
        "saturated_fat": 0.3,
        "unsaturated_fat": 1.5,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 50, "C": 60, "D": 0, "E": 15, "K": 200, "B6": 12},
        "minerals": {"sodium": 80, "potassium": 300, "calcium": 50, "iron": 10},
        "gi_index": 10,
        "positive_percent": 85,
        "negative_percent": 15,
    },
    "tuxum-salati": {
        "name": "Tuxum salati",
        "category": "salat",
        "image": "assets/img/salatlar/tuxumli salat.jpg",
        "calories": 140,
        "protein": 10,
        "fat": 10,
        "carbs": 2,
        "fiber": 0.5,
        "sugar": 1,
        "saturated_fat": 2.5,
        "unsaturated_fat": 6,
        "trans_fat": 0,
        "cholesterol": 350,
        "vitamins": {"A": 15, "C": 5, "D": 10, "E": 8, "K": 5, "B6": 10},
        "minerals": {"sodium": 300, "potassium": 150, "calcium": 50, "iron": 12},
        "gi_index": 10,
        "positive_percent": 60,
        "negative_percent": 40,
    },
    "qatiqli-sabzavot-salati": {
        "name": "Qatiqli sabzavot salati",
        "category": "salat",
        "image": "assets/img/salatlar/qatti sabzavot salat.jpg",
        "calories": 100,
        "protein": 4,
        "fat": 6,
        "carbs": 8,
        "fiber": 2,
        "sugar": 4,
        "saturated_fat": 3,
        "unsaturated_fat": 2,
        "trans_fat": 0,
        "cholesterol": 10,
        "vitamins": {"A": 20, "C": 25, "D": 2, "E": 5, "K": 20, "B6": 10},
        "minerals": {"sodium": 200, "potassium": 350, "calcium": 120, "iron": 6},
        "gi_index": 30,
        "positive_percent": 70,
        "negative_percent": 30,
    },
    "guruchli-salat": {
        "name": "Guruchli salat",
        "category": "salat",
        "image": "assets/img/salatlar/guruchli.jpg",
        "calories": 160,
        "protein": 4,
        "fat": 8,
        "carbs": 20,
        "fiber": 1,
        "sugar": 2,
        "saturated_fat": 1,
        "unsaturated_fat": 6,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 10, "C": 15, "D": 0, "E": 5, "K": 10, "B6": 12},
        "minerals": {"sodium": 350, "potassium": 180, "calcium": 20, "iron": 8},
        "gi_index": 55,
        "positive_percent": 55,
        "negative_percent": 45,
    },
    "mevali-salat": {
        "name": "Mevali salat",
        "category": "salat",
        "image": "assets/img/salatlar/mevali salat.jpg",
        "calories": 90,
        "protein": 1,
        "fat": 0.5,
        "carbs": 22,
        "fiber": 3,
        "sugar": 18,
        "saturated_fat": 0.1,
        "unsaturated_fat": 0.3,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 30, "C": 80, "D": 0, "E": 5, "K": 10, "B6": 15},
        "minerals": {"sodium": 10, "potassium": 350, "calcium": 25, "iron": 5},
        "gi_index": 50,
        "positive_percent": 80,
        "negative_percent": 20,
    },
    "pishloqli-salat": {
        "name": "Pishloqli salat",
        "category": "salat",
        "image": "assets/img/salatlar/pishloqli salat.jpg",
        "calories": 150,
        "protein": 8,
        "fat": 12,
        "carbs": 4,
        "fiber": 1,
        "sugar": 2,
        "saturated_fat": 7,
        "unsaturated_fat": 4,
        "trans_fat": 0.1,
        "cholesterol": 30,
        "vitamins": {"A": 15, "C": 15, "D": 1, "E": 3, "K": 15, "B6": 6},
        "minerals": {"sodium": 550, "potassium": 200, "calcium": 200, "iron": 5},
        "gi_index": 20,
        "positive_percent": 65,
        "negative_percent": 35,
    },
    "vitaminli-salat": {
        "name": "Vitaminli sabzavot salati",
        "category": "salat",
        "image": "assets/img/salatlar/vitaminli salat.jpg",
        "calories": 70,
        "protein": 2,
        "fat": 4,
        "carbs": 7,
        "fiber": 3,
        "sugar": 4,
        "saturated_fat": 0.5,
        "unsaturated_fat": 3,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 60, "C": 70, "D": 0, "E": 15, "K": 60, "B6": 15},
        "minerals": {"sodium": 100, "potassium": 400, "calcium": 40, "iron": 8},
        "gi_index": 15,
        "positive_percent": 85,
        "negative_percent": 15,
    },

    # ============ DESERTLAR ============
    "chak-chak": {
        "name": "Chak-chak",
        "category": "desert",
        "image": "assets/img/desertlar/chak chak.jpg",
        "calories": 420,
        "protein": 6,
        "fat": 18,
        "carbs": 60,
        "fiber": 1,
        "sugar": 35,
        "saturated_fat": 4,
        "unsaturated_fat": 12,
        "trans_fat": 0.5,
        "cholesterol": 40,
        "vitamins": {"A": 2, "C": 0, "D": 1, "E": 3, "K": 2, "B6": 5},
        "minerals": {"sodium": 120, "potassium": 100, "calcium": 30, "iron": 10},
        "gi_index": 75,
        "positive_percent": 40,
        "negative_percent": 60,
    },
    "halva": {
        "name": "Halva",
        "category": "desert",
        "image": "assets/img/desertlar/halva.jpg",
        "calories": 500,
        "protein": 12,
        "fat": 30,
        "carbs": 50,
        "fiber": 3,
        "sugar": 40,
        "saturated_fat": 5,
        "unsaturated_fat": 22,
        "trans_fat": 0.2,
        "cholesterol": 0,
        "vitamins": {"A": 0, "C": 0, "D": 0, "E": 25, "K": 0, "B6": 10},
        "minerals": {"sodium": 80, "potassium": 350, "calcium": 100, "iron": 15},
        "gi_index": 70,
        "positive_percent": 50,
        "negative_percent": 50,
    },
    "pahlava": {
        "name": "Pahlava",
        "category": "desert",
        "image": "assets/img/desertlar/pahlava.jpg",
        "calories": 460,
        "protein": 8,
        "fat": 25,
        "carbs": 55,
        "fiber": 2,
        "sugar": 40,
        "saturated_fat": 8,
        "unsaturated_fat": 15,
        "trans_fat": 0.3,
        "cholesterol": 30,
        "vitamins": {"A": 5, "C": 2, "D": 0, "E": 10, "K": 3, "B6": 8},
        "minerals": {"sodium": 150, "potassium": 200, "calcium": 50, "iron": 12},
        "gi_index": 70,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "medovik": {
        "name": "Medovik",
        "category": "desert",
        "image": "assets/img/desertlar/medovik.jpg",
        "calories": 400,
        "protein": 5,
        "fat": 20,
        "carbs": 52,
        "fiber": 0.5,
        "sugar": 35,
        "saturated_fat": 12,
        "unsaturated_fat": 6,
        "trans_fat": 0.5,
        "cholesterol": 80,
        "vitamins": {"A": 8, "C": 0, "D": 2, "E": 3, "K": 2, "B6": 4},
        "minerals": {"sodium": 200, "potassium": 120, "calcium": 50, "iron": 8},
        "gi_index": 68,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "napoleon": {
        "name": "Napoleon",
        "category": "desert",
        "image": "assets/img/desertlar/napaleon.jpg",
        "calories": 380,
        "protein": 5,
        "fat": 22,
        "carbs": 42,
        "fiber": 0.5,
        "sugar": 25,
        "saturated_fat": 14,
        "unsaturated_fat": 6,
        "trans_fat": 1,
        "cholesterol": 90,
        "vitamins": {"A": 10, "C": 0, "D": 2, "E": 2, "K": 3, "B6": 3},
        "minerals": {"sodium": 250, "potassium": 100, "calcium": 40, "iron": 6},
        "gi_index": 65,
        "positive_percent": 35,
        "negative_percent": 65,
    },
    "shokoladli-tort": {
        "name": "Shokoladli tort",
        "category": "desert",
        "image": "assets/img/desertlar/shokoladli tort.jpg",
        "calories": 420,
        "protein": 5,
        "fat": 22,
        "carbs": 52,
        "fiber": 2,
        "sugar": 40,
        "saturated_fat": 12,
        "unsaturated_fat": 8,
        "trans_fat": 0.5,
        "cholesterol": 60,
        "vitamins": {"A": 5, "C": 0, "D": 1, "E": 3, "K": 2, "B6": 4},
        "minerals": {"sodium": 300, "potassium": 250, "calcium": 50, "iron": 15},
        "gi_index": 70,
        "positive_percent": 40,
        "negative_percent": 60,
    },
    "tiramisu": {
        "name": "Tiramisu",
        "category": "desert",
        "image": "assets/img/desertlar/tiramisu.jpg",
        "calories": 350,
        "protein": 6,
        "fat": 20,
        "carbs": 38,
        "fiber": 0.5,
        "sugar": 28,
        "saturated_fat": 12,
        "unsaturated_fat": 6,
        "trans_fat": 0.3,
        "cholesterol": 120,
        "vitamins": {"A": 12, "C": 0, "D": 2, "E": 2, "K": 2, "B6": 5},
        "minerals": {"sodium": 100, "potassium": 150, "calcium": 80, "iron": 6},
        "gi_index": 55,
        "positive_percent": 40,
        "negative_percent": 60,
    },
    "chizkeyk": {
        "name": "Chizkeyk",
        "category": "desert",
        "image": "assets/img/desertlar/chizkeyk.jpg",
        "calories": 360,
        "protein": 6,
        "fat": 24,
        "carbs": 32,
        "fiber": 0.5,
        "sugar": 22,
        "saturated_fat": 14,
        "unsaturated_fat": 8,
        "trans_fat": 0.4,
        "cholesterol": 100,
        "vitamins": {"A": 15, "C": 2, "D": 2, "E": 2, "K": 3, "B6": 4},
        "minerals": {"sodium": 350, "potassium": 150, "calcium": 100, "iron": 5},
        "gi_index": 55,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "brauni": {
        "name": "Brauni",
        "category": "desert",
        "image": "assets/img/desertlar/brauni.jpg",
        "calories": 410,
        "protein": 5,
        "fat": 20,
        "carbs": 55,
        "fiber": 3,
        "sugar": 40,
        "saturated_fat": 10,
        "unsaturated_fat": 8,
        "trans_fat": 0.3,
        "cholesterol": 50,
        "vitamins": {"A": 3, "C": 0, "D": 1, "E": 4, "K": 2, "B6": 3},
        "minerals": {"sodium": 150, "potassium": 200, "calcium": 30, "iron": 15},
        "gi_index": 65,
        "positive_percent": 35,
        "negative_percent": 65,
    },
    "limonli-tart": {
        "name": "Limonli tart",
        "category": "desert",
        "image": "assets/img/desertlar/limonli tort.jpg",
        "calories": 330,
        "protein": 4,
        "fat": 15,
        "carbs": 46,
        "fiber": 1,
        "sugar": 30,
        "saturated_fat": 8,
        "unsaturated_fat": 5,
        "trans_fat": 0.3,
        "cholesterol": 70,
        "vitamins": {"A": 5, "C": 20, "D": 1, "E": 2, "K": 2, "B6": 4},
        "minerals": {"sodium": 180, "potassium": 100, "calcium": 25, "iron": 5},
        "gi_index": 60,
        "positive_percent": 50,
        "negative_percent": 50,
    },
    "merenga-ruleti": {
        "name": "Merenga ruleti",
        "category": "desert",
        "image": "assets/img/desertlar/merenga ruleti.jpg",
        "calories": 370,
        "protein": 5,
        "fat": 18,
        "carbs": 50,
        "fiber": 0.5,
        "sugar": 45,
        "saturated_fat": 10,
        "unsaturated_fat": 6,
        "trans_fat": 0.2,
        "cholesterol": 40,
        "vitamins": {"A": 8, "C": 10, "D": 1, "E": 2, "K": 2, "B6": 3},
        "minerals": {"sodium": 80, "potassium": 120, "calcium": 30, "iron": 3},
        "gi_index": 75,
        "positive_percent": 40,
        "negative_percent": 60,
    },
    "matcha-ruleti": {
        "name": "Matcha ruleti",
        "category": "desert",
        "image": "assets/img/desertlar/matcha ruleti.jpg",
        "calories": 340,
        "protein": 6,
        "fat": 16,
        "carbs": 44,
        "fiber": 1,
        "sugar": 30,
        "saturated_fat": 9,
        "unsaturated_fat": 5,
        "trans_fat": 0.2,
        "cholesterol": 60,
        "vitamins": {"A": 10, "C": 5, "D": 1, "E": 5, "K": 20, "B6": 5},
        "minerals": {"sodium": 100, "potassium": 180, "calcium": 50, "iron": 8},
        "gi_index": 55,
        "positive_percent": 50,
        "negative_percent": 50,
    },
    "olchali-brauni": {
        "name": "Olchali brauni",
        "category": "desert",
        "image": "assets/img/desertlar/olchali brauni.jpg",
        "calories": 390,
        "protein": 5,
        "fat": 18,
        "carbs": 54,
        "fiber": 3,
        "sugar": 38,
        "saturated_fat": 9,
        "unsaturated_fat": 7,
        "trans_fat": 0.2,
        "cholesterol": 45,
        "vitamins": {"A": 8, "C": 5, "D": 1, "E": 4, "K": 3, "B6": 4},
        "minerals": {"sodium": 140, "potassium": 220, "calcium": 30, "iron": 12},
        "gi_index": 60,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "nokli-brauni": {
        "name": "Nokli brauni",
        "category": "desert",
        "image": "assets/img/desertlar/nokli brauni.jpg",
        "calories": 380,
        "protein": 5,
        "fat": 18,
        "carbs": 52,
        "fiber": 3,
        "sugar": 35,
        "saturated_fat": 8,
        "unsaturated_fat": 8,
        "trans_fat": 0.2,
        "cholesterol": 45,
        "vitamins": {"A": 3, "C": 3, "D": 1, "E": 4, "K": 3, "B6": 4},
        "minerals": {"sodium": 130, "potassium": 200, "calcium": 28, "iron": 10},
        "gi_index": 58,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "qush-suti": {
        "name": "Qush suti",
        "category": "desert",
        "image": "assets/img/desertlar/qush suti.jpg",
        "calories": 360,
        "protein": 8,
        "fat": 18,
        "carbs": 42,
        "fiber": 0,
        "sugar": 35,
        "saturated_fat": 10,
        "unsaturated_fat": 6,
        "trans_fat": 0.3,
        "cholesterol": 100,
        "vitamins": {"A": 12, "C": 0, "D": 3, "E": 2, "K": 2, "B6": 5},
        "minerals": {"sodium": 120, "potassium": 150, "calcium": 100, "iron": 4},
        "gi_index": 65,
        "positive_percent": 40,
        "negative_percent": 60,
    },
    "bananli-keks": {
        "name": "Bananli keks",
        "category": "desert",
        "image": "assets/img/desertlar/bananli keks.jpg",
        "calories": 350,
        "protein": 5,
        "fat": 15,
        "carbs": 52,
        "fiber": 2,
        "sugar": 30,
        "saturated_fat": 5,
        "unsaturated_fat": 8,
        "trans_fat": 0.2,
        "cholesterol": 50,
        "vitamins": {"A": 3, "C": 8, "D": 1, "E": 3, "K": 2, "B6": 20},
        "minerals": {"sodium": 250, "potassium": 350, "calcium": 30, "iron": 8},
        "gi_index": 60,
        "positive_percent": 50,
        "negative_percent": 50,
    },
    "chia-pudingi": {
        "name": "Chia pudingi",
        "category": "desert",
        "image": "assets/img/desertlar/chia puddingi.jpg",
        "calories": 180,
        "protein": 5,
        "fat": 9,
        "carbs": 22,
        "fiber": 10,
        "sugar": 8,
        "saturated_fat": 1,
        "unsaturated_fat": 7,
        "trans_fat": 0,
        "cholesterol": 5,
        "vitamins": {"A": 2, "C": 2, "D": 5, "E": 3, "K": 5, "B6": 5},
        "minerals": {"sodium": 50, "potassium": 200, "calcium": 180, "iron": 15},
        "gi_index": 25,
        "positive_percent": 70,
        "negative_percent": 30,
    },
    "qahvali-desert": {
        "name": "Qahvali desert",
        "category": "desert",
        "image": "assets/img/desertlar/qahvali desert.jpg",
        "calories": 300,
        "protein": 5,
        "fat": 16,
        "carbs": 36,
        "fiber": 1,
        "sugar": 25,
        "saturated_fat": 9,
        "unsaturated_fat": 5,
        "trans_fat": 0.2,
        "cholesterol": 60,
        "vitamins": {"A": 8, "C": 0, "D": 2, "E": 2, "K": 2, "B6": 4},
        "minerals": {"sodium": 100, "potassium": 200, "calcium": 60, "iron": 6},
        "gi_index": 55,
        "positive_percent": 45,
        "negative_percent": 55,
    },
    "murabbo": {
        "name": "Murabbo",
        "category": "desert",
        "image": "assets/img/desertlar/murabbo.jpg",
        "calories": 250,
        "protein": 0.5,
        "fat": 0.2,
        "carbs": 65,
        "fiber": 1,
        "sugar": 60,
        "saturated_fat": 0,
        "unsaturated_fat": 0.1,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 5, "C": 15, "D": 0, "E": 2, "K": 2, "B6": 3},
        "minerals": {"sodium": 10, "potassium": 100, "calcium": 20, "iron": 3},
        "gi_index": 70,
        "positive_percent": 55,
        "negative_percent": 45,
    },
    "quritilgan-mevalar": {
        "name": "Quritilgan mevalar",
        "category": "desert",
        "image": "assets/img/desertlar/quritilgan mevalar.jpg",
        "calories": 220,
        "protein": 3,
        "fat": 0.5,
        "carbs": 55,
        "fiber": 7,
        "sugar": 45,
        "saturated_fat": 0.1,
        "unsaturated_fat": 0.3,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 10, "C": 5, "D": 0, "E": 3, "K": 8, "B6": 15},
        "minerals": {"sodium": 15, "potassium": 750, "calcium": 50, "iron": 12},
        "gi_index": 55,
        "positive_percent": 75,
        "negative_percent": 25,
    },

    # ============ MILLIY TAOMLAR ============
    "osh": {
        "name": "Osh (palov)",
        "category": "taom",
        "image": "assets/img/taomlar/osh palov.jpg",
        "calories": 200,
        "protein": 8,
        "fat": 12,
        "carbs": 18,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 3,
        "unsaturated_fat": 8,
        "trans_fat": 0.2,
        "cholesterol": 25,
        "vitamins": {"A": 25, "C": 5, "D": 0, "E": 5, "K": 5, "B6": 15},
        "minerals": {"sodium": 450, "potassium": 250, "calcium": 20, "iron": 12},
        "gi_index": 60,
        "positive_percent": 50,
        "negative_percent": 50,
        "animal_protein": 6,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "Yuqori",
    },
    "palov": {
        "name": "Osh (palov)",
        "category": "taom",
        "image": "assets/img/taomlar/osh palov.jpg",
        "calories": 200,
        "protein": 8,
        "fat": 12,
        "carbs": 18,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 3,
        "unsaturated_fat": 8,
        "trans_fat": 0.2,
        "cholesterol": 25,
        "vitamins": {"A": 25, "C": 5, "D": 0, "E": 5, "K": 5, "B6": 15},
        "minerals": {"sodium": 450, "potassium": 250, "calcium": 20, "iron": 12},
        "gi_index": 60,
        "positive_percent": 50,
        "negative_percent": 50,
        "animal_protein": 6,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "Yuqori",
    },
    "shashlik": {
        "name": "Shashlik (kabob)",
        "category": "taom",
        "image": "assets/img/taomlar/shashlik.jpg",
        "calories": 220,
        "protein": 25,
        "fat": 13,
        "carbs": 1,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 5,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 80,
        "vitamins": {"A": 0, "C": 0, "D": 1, "E": 2, "K": 3, "B6": 30},
        "minerals": {"sodium": 380, "potassium": 350, "calcium": 15, "iron": 18},
        "gi_index": 0,
        "positive_percent": 65,
        "negative_percent": 35,
        "animal_protein": 25,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "kabob": {
        "name": "Shashlik (kabob)",
        "category": "taom",
        "image": "assets/img/taomlar/shashlik.jpg",
        "calories": 220,
        "protein": 25,
        "fat": 13,
        "carbs": 1,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 5,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 80,
        "vitamins": {"A": 0, "C": 0, "D": 1, "E": 2, "K": 3, "B6": 30},
        "minerals": {"sodium": 380, "potassium": 350, "calcium": 15, "iron": 18},
        "gi_index": 0,
        "positive_percent": 65,
        "negative_percent": 35,
        "animal_protein": 25,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "manti": {
        "name": "Manti",
        "category": "taom",
        "image": "assets/img/taomlar/manti.jpg",
        "calories": 250,
        "protein": 12,
        "fat": 14,
        "carbs": 20,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 5,
        "unsaturated_fat": 8,
        "trans_fat": 0.2,
        "cholesterol": 45,
        "vitamins": {"A": 3, "C": 3, "D": 0, "E": 3, "K": 3, "B6": 15},
        "minerals": {"sodium": 400, "potassium": 200, "calcium": 25, "iron": 15},
        "gi_index": 55,
        "positive_percent": 55,
        "negative_percent": 45,
        "animal_protein": 10,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "Yuqori",
    },
    "lagmon": {
        "name": "Lag'mon",
        "category": "taom",
        "image": "assets/img/taomlar/lagmon.jpg",
        "calories": 180,
        "protein": 10,
        "fat": 8,
        "carbs": 18,
        "fiber": 2,
        "sugar": 3,
        "saturated_fat": 2,
        "unsaturated_fat": 5,
        "trans_fat": 0.1,
        "cholesterol": 30,
        "vitamins": {"A": 20, "C": 15, "D": 0, "E": 4, "K": 10, "B6": 15},
        "minerals": {"sodium": 550, "potassium": 300, "calcium": 30, "iron": 12},
        "gi_index": 50,
        "positive_percent": 60,
        "negative_percent": 40,
        "animal_protein": 8,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "somsa": {
        "name": "Somsa",
        "category": "taom",
        "image": "assets/img/taomlar/somsa.jpg",
        "calories": 270,
        "protein": 10,
        "fat": 16,
        "carbs": 22,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 6,
        "unsaturated_fat": 9,
        "trans_fat": 0.3,
        "cholesterol": 35,
        "vitamins": {"A": 3, "C": 3, "D": 0, "E": 3, "K": 3, "B6": 10},
        "minerals": {"sodium": 480, "potassium": 180, "calcium": 25, "iron": 12},
        "gi_index": 55,
        "positive_percent": 50,
        "negative_percent": 50,
        "animal_protein": 8,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "chuchvara": {
        "name": "Chuchvara",
        "category": "taom",
        "image": "assets/img/taomlar/chuchvara.jpg",
        "calories": 210,
        "protein": 10,
        "fat": 10,
        "carbs": 20,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 3,
        "unsaturated_fat": 6,
        "trans_fat": 0.1,
        "cholesterol": 35,
        "vitamins": {"A": 3, "C": 3, "D": 0, "E": 3, "K": 3, "B6": 12},
        "minerals": {"sodium": 420, "potassium": 180, "calcium": 25, "iron": 12},
        "gi_index": 50,
        "positive_percent": 55,
        "negative_percent": 45,
        "animal_protein": 8,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "sumalak": {
        "name": "Sumalak",
        "category": "taom",
        "image": "assets/img/taomlar/sumlak.jpg",
        "calories": 160,
        "protein": 3,
        "fat": 1,
        "carbs": 35,
        "fiber": 2,
        "sugar": 25,
        "saturated_fat": 0.2,
        "unsaturated_fat": 0.5,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 0, "C": 0, "D": 0, "E": 10, "K": 5, "B6": 15},
        "minerals": {"sodium": 20, "potassium": 200, "calcium": 30, "iron": 10},
        "gi_index": 65,
        "positive_percent": 75,
        "negative_percent": 25,
        "animal_protein": 0,
        "plant_protein": 3,
        "amino_acids": "O'rta",
        "protein_quality": "O'rta",
    },
    "norin": {
        "name": "Norin",
        "category": "taom",
        "image": "assets/img/taomlar/norin.jpg",
        "calories": 230,
        "protein": 15,
        "fat": 12,
        "carbs": 18,
        "fiber": 1,
        "sugar": 0,
        "saturated_fat": 4,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 50,
        "vitamins": {"A": 2, "C": 2, "D": 0, "E": 3, "K": 3, "B6": 20},
        "minerals": {"sodium": 500, "potassium": 220, "calcium": 20, "iron": 15},
        "gi_index": 50,
        "positive_percent": 50,
        "negative_percent": 50,
        "animal_protein": 15,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "qovurma-gosht": {
        "name": "Qovurma go'sht",
        "category": "taom",
        "image": "assets/img/taomlar/qovurma gosht.jpg",
        "calories": 250,
        "protein": 20,
        "fat": 18,
        "carbs": 3,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 7,
        "unsaturated_fat": 10,
        "trans_fat": 0.2,
        "cholesterol": 70,
        "vitamins": {"A": 0, "C": 0, "D": 1, "E": 2, "K": 2, "B6": 25},
        "minerals": {"sodium": 450, "potassium": 320, "calcium": 15, "iron": 18},
        "gi_index": 0,
        "positive_percent": 45,
        "negative_percent": 55,
        "animal_protein": 20,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "tandir-gosht": {
        "name": "Tandir go'sht",
        "category": "taom",
        "image": "assets/img/taomlar/tandir gosht.jpg",
        "calories": 220,
        "protein": 22,
        "fat": 14,
        "carbs": 1,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 5,
        "unsaturated_fat": 8,
        "trans_fat": 0.1,
        "cholesterol": 75,
        "vitamins": {"A": 0, "C": 0, "D": 1, "E": 2, "K": 2, "B6": 28},
        "minerals": {"sodium": 400, "potassium": 350, "calcium": 15, "iron": 20},
        "gi_index": 0,
        "positive_percent": 65,
        "negative_percent": 35,
        "animal_protein": 22,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "qozon-kabob": {
        "name": "Qozon kabob",
        "category": "taom",
        "image": "assets/img/taomlar/qozon kabob.jpg",
        "calories": 240,
        "protein": 18,
        "fat": 16,
        "carbs": 6,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 6,
        "unsaturated_fat": 9,
        "trans_fat": 0.2,
        "cholesterol": 65,
        "vitamins": {"A": 5, "C": 10, "D": 0, "E": 3, "K": 5, "B6": 22},
        "minerals": {"sodium": 420, "potassium": 380, "calcium": 18, "iron": 16},
        "gi_index": 30,
        "positive_percent": 55,
        "negative_percent": 45,
        "animal_protein": 18,
        "plant_protein": 0,
        "amino_acids": "Yaxshi",
        "protein_quality": "Yuqori",
    },
    "dolma": {
        "name": "Dolma",
        "category": "taom",
        "image": "assets/img/taomlar/dolma.jpg",
        "calories": 180,
        "protein": 10,
        "fat": 10,
        "carbs": 14,
        "fiber": 3,
        "sugar": 2,
        "saturated_fat": 3,
        "unsaturated_fat": 6,
        "trans_fat": 0.1,
        "cholesterol": 30,
        "vitamins": {"A": 40, "C": 20, "D": 0, "E": 5, "K": 50, "B6": 15},
        "minerals": {"sodium": 350, "potassium": 400, "calcium": 50, "iron": 15},
        "gi_index": 40,
        "positive_percent": 70,
        "negative_percent": 30,
        "animal_protein": 8,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "mastava": {
        "name": "Mastava",
        "category": "taom",
        "image": "assets/img/taomlar/mastava.jpg",
        "calories": 120,
        "protein": 6,
        "fat": 5,
        "carbs": 14,
        "fiber": 1,
        "sugar": 2,
        "saturated_fat": 1.5,
        "unsaturated_fat": 3,
        "trans_fat": 0,
        "cholesterol": 20,
        "vitamins": {"A": 15, "C": 10, "D": 0, "E": 3, "K": 8, "B6": 10},
        "minerals": {"sodium": 600, "potassium": 280, "calcium": 40, "iron": 8},
        "gi_index": 55,
        "positive_percent": 80,
        "negative_percent": 20,
        "animal_protein": 4,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "shorva": {
        "name": "Sho'rva",
        "category": "taom",
        "image": "assets/img/taomlar/shorva.jpg",
        "calories": 100,
        "protein": 8,
        "fat": 5,
        "carbs": 6,
        "fiber": 1,
        "sugar": 2,
        "saturated_fat": 2,
        "unsaturated_fat": 2.5,
        "trans_fat": 0,
        "cholesterol": 25,
        "vitamins": {"A": 20, "C": 15, "D": 0, "E": 2, "K": 10, "B6": 12},
        "minerals": {"sodium": 700, "potassium": 350, "calcium": 25, "iron": 10},
        "gi_index": 40,
        "positive_percent": 80,
        "negative_percent": 20,
        "animal_protein": 6,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "beshbarmoq": {
        "name": "Beshbarmoq",
        "category": "taom",
        "image": "assets/img/taomlar/beshbarmoq.jpg",
        "calories": 230,
        "protein": 14,
        "fat": 12,
        "carbs": 18,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 4,
        "unsaturated_fat": 7,
        "trans_fat": 0.1,
        "cholesterol": 45,
        "vitamins": {"A": 2, "C": 3, "D": 0, "E": 3, "K": 3, "B6": 18},
        "minerals": {"sodium": 480, "potassium": 250, "calcium": 25, "iron": 14},
        "gi_index": 55,
        "positive_percent": 55,
        "negative_percent": 45,
        "animal_protein": 14,
        "plant_protein": 0,
        "amino_acids": "Yaxshi",
        "protein_quality": "Yuqori",
    },
    "qazi": {
        "name": "Qazi",
        "category": "taom",
        "image": "assets/img/taomlar/qazi.jpg",
        "calories": 300,
        "protein": 18,
        "fat": 25,
        "carbs": 0,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 10,
        "unsaturated_fat": 13,
        "trans_fat": 0.3,
        "cholesterol": 85,
        "vitamins": {"A": 0, "C": 0, "D": 1, "E": 2, "K": 2, "B6": 20},
        "minerals": {"sodium": 900, "potassium": 280, "calcium": 10, "iron": 15},
        "gi_index": 0,
        "positive_percent": 40,
        "negative_percent": 60,
        "animal_protein": 18,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "tandir-somsa": {
        "name": "Tandir somsa",
        "category": "taom",
        "image": "assets/img/taomlar/tandir somsa.jpg",
        "calories": 280,
        "protein": 11,
        "fat": 15,
        "carbs": 26,
        "fiber": 1,
        "sugar": 1,
        "saturated_fat": 5,
        "unsaturated_fat": 9,
        "trans_fat": 0.2,
        "cholesterol": 35,
        "vitamins": {"A": 3, "C": 3, "D": 0, "E": 3, "K": 3, "B6": 10},
        "minerals": {"sodium": 500, "potassium": 180, "calcium": 25, "iron": 12},
        "gi_index": 55,
        "positive_percent": 50,
        "negative_percent": 50,
        "animal_protein": 9,
        "plant_protein": 2,
        "amino_acids": "Yaxshi",
        "protein_quality": "O'rta",
    },
    "baliq-kabob": {
        "name": "Balik kabob",
        "category": "taom",
        "image": "assets/img/taomlar/baliq kabob.jpg",
        "calories": 190,
        "protein": 22,
        "fat": 10,
        "carbs": 2,
        "fiber": 0,
        "sugar": 0,
        "saturated_fat": 2,
        "unsaturated_fat": 7,
        "trans_fat": 0,
        "cholesterol": 60,
        "vitamins": {"A": 2, "C": 0, "D": 30, "E": 5, "K": 2, "B6": 25},
        "minerals": {"sodium": 350, "potassium": 400, "calcium": 30, "iron": 8},
        "gi_index": 0,
        "positive_percent": 70,
        "negative_percent": 30,
        "animal_protein": 22,
        "plant_protein": 0,
        "amino_acids": "A'lo",
        "protein_quality": "Yuqori",
    },
    "qovun": {
        "name": "Qovun",
        "category": "taom",
        "image": "assets/img/taomlar/qovun.png",
        "calories": 40,
        "protein": 1,
        "fat": 0.2,
        "carbs": 9,
        "fiber": 1,
        "sugar": 8,
        "saturated_fat": 0,
        "unsaturated_fat": 0.1,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 70, "C": 40, "D": 0, "E": 2, "K": 3, "B6": 10},
        "minerals": {"sodium": 15, "potassium": 270, "calcium": 10, "iron": 3},
        "gi_index": 65,
        "positive_percent": 90,
        "negative_percent": 10,
        "animal_protein": 0,
        "plant_protein": 1,
        "amino_acids": "Kam",
        "protein_quality": "Past",
    },
    "non": {
        "name": "Non (tandir non)",
        "category": "taom",
        "image": "assets/img/taomlar/non.jpg",
        "calories": 250,
        "protein": 8,
        "fat": 2,
        "carbs": 50,
        "fiber": 2,
        "sugar": 2,
        "saturated_fat": 0.5,
        "unsaturated_fat": 1,
        "trans_fat": 0,
        "cholesterol": 0,
        "vitamins": {"A": 0, "C": 0, "D": 0, "E": 3, "K": 2, "B6": 8},
        "minerals": {"sodium": 500, "potassium": 120, "calcium": 25, "iron": 15},
        "gi_index": 70,
        "positive_percent": 60,
        "negative_percent": 40,
        "animal_protein": 0,
        "plant_protein": 8,
        "amino_acids": "O'rta",
        "protein_quality": "O'rta",
    },
}

# Qidirish uchun nom variantlarini sozlash
SEARCH_ALIASES = {
    # Salatlar
    "achchiq chuchuk": "achchiq-chuchuk",
    "achiq-chuchuk": "achchiq-chuchuk",
    "achiq chuchuk": "achchiq-chuchuk",
    "olivier": "olivye",
    "olivie": "olivye",
    "olivye salat": "olivye",
    "sezar salat": "sezar",
    "caesar": "sezar",
    "caesar salad": "sezar",
    "grek salat": "yunoncha-salat",
    "yunoncha": "yunoncha-salat",
    "greek salad": "yunoncha-salat",
    "mimoza salat": "mimoza",
    "sabzavot salat": "sabzavotli-salat",
    "sabzavotli": "sabzavotli-salat",
    "bodring pomidor": "bodring-pomidor",
    "pomidor bodring": "bodring-pomidor",
    "kartoshka salat": "kartoshka-salati",
    "kartoshkali salat": "kartoshka-salati",
    "potato salad": "kartoshka-salati",
    "tovuq salat": "tovuq-salati",
    "tovuqli salat": "tovuq-salati",
    "chicken salad": "tovuq-salati",
    "baliq salat": "baliqli-salat",
    "baliqli": "baliqli-salat",
    "fish salad": "baliqli-salat",
    "qovoq": "qovoq-salati",
    "lavlagi": "lavlagi-salati",
    "kokatli": "kokatli-salat",
    "tuxum salat": "tuxum-salati",
    "tuxumli salat": "tuxum-salati",
    "qatiqli salat": "qatiqli-sabzavot-salati",
    "guruchli": "guruchli-salat",
    "mevali": "mevali-salat",
    "fruit salad": "mevali-salat",
    "pishloqli": "pishloqli-salat",
    "cheese salad": "pishloqli-salat",
    "vitaminli": "vitaminli-salat",
    
    # Desertlar
    "chak chak": "chak-chak",
    "chakchak": "chak-chak",
    "xalva": "halva",
    "halvah": "halva",
    "baklava": "pahlava",
    "baklawa": "pahlava",
    "honey cake": "medovik",
    "asal tort": "medovik",
    "napaleon": "napoleon",
    "napoleon tort": "napoleon",
    "shokolad tort": "shokoladli-tort",
    "chocolate cake": "shokoladli-tort",
    "cheesecake": "chizkeyk",
    "pishloq tort": "chizkeyk",
    "brownie": "brauni",
    "limon tart": "limonli-tart",
    "lemon tart": "limonli-tart",
    "merenga": "merenga-ruleti",
    "meringue roll": "merenga-ruleti",
    "matcha": "matcha-ruleti",
    "olcha brauni": "olchali-brauni",
    "cherry brownie": "olchali-brauni",
    "nok brauni": "nokli-brauni",
    "pear brownie": "nokli-brauni",
    "qush sut": "qush-suti",
    "birds milk": "qush-suti",
    "banana bread": "bananli-keks",
    "banan keks": "bananli-keks",
    "chia pudding": "chia-pudingi",
    "chia": "chia-pudingi",
    "qahva desert": "qahvali-desert",
    "coffee dessert": "qahvali-desert",
    "jam": "murabbo",
    "quritilgan meva": "quritilgan-mevalar",
    "dried fruits": "quritilgan-mevalar",
    
    # Milliy taomlar
    "plov": "osh",
    "pilaf": "osh",
    "pilav": "osh",
    "ash": "osh",
    "osh palov": "osh",
    "uzbek plov": "osh",
    "kabab": "shashlik",
    "kebab": "shashlik",
    "shish kebab": "shashlik",
    "dumplings": "manti",
    "mantuu": "manti",
    "lagman": "lagmon",
    "uyghur noodles": "lagmon",
    "samsa": "somsa",
    "samosa": "somsa",
    "pelmeni": "chuchvara",
    "sumalak": "sumalak",
    "halim": "sumalak",
    "naryn": "norin",
    "qovurma": "qovurma-gosht",
    "qovurdoq": "qovurma-gosht",
    "tandir": "tandir-gosht",
    "qozan kabob": "qozon-kabob",
    "kazan kebab": "qozon-kabob",
    "dolma": "dolma",
    "stuffed grape leaves": "dolma",
    "soup": "mastava",
    "shurpa": "shorva",
    "shorba": "shorva",
    "beshbarmak": "beshbarmoq",
    "besbarmoq": "beshbarmoq",
    "horse sausage": "qazi",
    "kazy": "qazi",
    "tandir samsa": "tandir-somsa",
    "fish kebab": "baliq-kabob",
    "baliq": "baliq-kabob",
    "melon": "qovun",
    "bread": "non",
    "nan": "non",
    "lepeshka": "non",
}


def search_food(query):
    """
    Taomni qidirish funksiyasi
    Qidirish tartib bo'yicha to'g'ri moslikdan yaqin moslikka
    """
    if not query:
        return None
    
    query = query.lower().strip()
    
    # 1. To'g'ridan-to'g'ri moslik
    if query in FOOD_DATA:
        return FOOD_DATA[query]
    
    # 2. Aliaslar bo'yicha qidirish
    if query in SEARCH_ALIASES:
        key = SEARCH_ALIASES[query]
        if key in FOOD_DATA:
            return FOOD_DATA[key]
    
    # 3. Partial match - nom boshida
    for key, data in FOOD_DATA.items():
        if key.startswith(query) or data['name'].lower().startswith(query):
            return data
    
    # 4. Partial match - nom ichida
    for key, data in FOOD_DATA.items():
        if query in key or query in data['name'].lower():
            return data
    
    # 5. Alias partial match
    for alias, key in SEARCH_ALIASES.items():
        if query in alias:
            if key in FOOD_DATA:
                return FOOD_DATA[key]
    
    return None


def get_all_foods():
    """Barcha taomlar ro'yxatini qaytarish"""
    return list(FOOD_DATA.values())


def get_foods_by_category(category):
    """Kategoriya bo'yicha taomlarni qaytarish"""
    return [food for food in FOOD_DATA.values() if food['category'] == category]


def get_default_food():
    """Default taomni qaytarish (osh/palov)"""
    return FOOD_DATA.get('osh')
